name: 'Figma Cursor Theme Generator'
description: 'GitHub Action that generates a cursor theme from a Figma file.'
inputs:
  figma_access_token:
    description: 'Your personal Figma access token.'
    required: true
  figma_file_key:
    description: 'The `key` of the Figma file containing the cursor theme. Can be found in the url to of a figma file. `https://www.figma.com/file/:key/:title`'
    required: true
  sprite_component_set_id:
    description: 'Figma node ID of the sprite component set.'
    required: true
  alias_component_set_id:
    description: 'Figma node ID of the alias component set.'
    required: true
  theme_name:
    description: 'Name of the cursor theme.'
    required: true
    default: 'Generated Cursor Theme'
  theme_comment:
    description: 'Short comment or description of the cursor theme.'
    required: false
    default: 'This is a generated cursor theme.'
  theme_directory:
    description: 'Output directory for the cursor theme variants.'
    required: true
    default: build/themes
  export_directory:
    description: 'Output directory for exports defined in the Figma file.'
  svg_directory:
    description: 'Output directory for SVG images of all cursor sprites.'
  scales:
    description: 'List of target scales the cursors will be rendered at.'
    default: '1, 2, 4'
outputs:
  version:
    description: 'The current version of the Figma file.'

runs:
  using: 'node16'
  main: 'dist/index.js'
